image: php:7.1

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375

before_script:
  - composer install

cache:
  paths:
  - vendor/

stages:
- Test

Test with coverage:
  stage: Test
  coverage: '/Lines:\s*\d+\.\d+%/'
  script:
  - vendor/bin/phpunit

PHPStan:
  stage: Test
  script:
  - vendor/bin/phpstan analyze

Check code style:
  stage: Test
  allow_failure: true
  script:
  - composer cs-check
